version: "3.2"
services:
  # 1 - NODEJS CONTAINER
  nodejs:
    build:
      context: ./src/back/
    image: marionlnd/ged-script
    networks:
      - frontend
      - backend
    environment:
      - MARIADB_HOST=ged-mariadb-app
      - MARIADB_USER=UserGed
      - MARIADB_PASS=GEDGROUPE4
      - MARIADB_DB=GED
    volumes:
      - C:\Users\houra\Documents\GED_PDF:/var/www/html # A REVERIFIER MAIS ON N'EN AURA PEUT-ETRE PAS BESOIN A LA FIN
    #  -./././Usershoura\Documents\GED_PDF
    ports:
      - "30001:8080"
    container_name: ged-nodejs-app
  # 2 - MARIADB CONTAINER
  mariadb:
    image: mariadb:10.5
    ports:
      - "30002:3306"
    volumes:
      - db_data:/var/lib/mariadb
      - ./src/back/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=UserGed
      - MARIADB_PASSWORD=GEDGROUPE4
      - MARIADB_DATABASE=GED
    container_name: ged-mariadb-app
  # 3 - PHPMYADMIN CONTAINER
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mariadb
    networks:
      - backend
    ports:
      - "30003:80"
    environment:
      - PMA_HOST=ged-mariadb-app
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: ged-phpmyadmin-app

networks:
  frontend:
  backend:

volumes:
  db_data:
